version: '3.8'

services:
  web:
    build: .
    command: python /Desktop/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Desktop
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: