version: '3.8'

services:
  web:
    build: .
    command: python /Desktop/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Desktop
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    environment:
      - NEW_SECRET_KEY=mi2o1*868#dosapipu6qke!7gw^eh+jp9a6!h)+@6%fq^11ekd
      - NEW_DEBUG=1
      - SENDGRID_API_KEY=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
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: